"""empty message

Revision ID: 907d0dec1971
Revises: e87ef88df848
Create Date: 2018-06-10 17:18:37.596109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907d0dec1971'
down_revision = 'e87ef88df848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'post', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
